# Generated by Django 2.2.1 on 2019-05-14 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('breed', models.CharField(max_length=32)),
                ('bday', models.DateField()),
                ('desc', models.CharField(max_length=256)),
                ('owners', models.ManyToManyField(related_name='dogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
